- name: 'Download binary from https://releases.mattermost.org'
  get_url:
    url: 'https://releases.mattermost.com/{{ mattermost_version }}/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz'
    dest: /tmp/

- name: Check if mattermost is already installed
  stat:
    path: /opt/mattermost
  register: mattermost_exists

- name: Clean up old files if this is an upgrade
  shell: find /opt/mattermost/ /opt/mattermost/client/ -mindepth 1 -maxdepth 1 \! \( -type d \( -path /opt/mattermost/client -o -path /opt/mattermost/client/plugins -o -path /opt/mattermost/config -o -path /opt/mattermost/logs -o -path /opt/mattermost/plugins -o -path /opt/mattermost/data \) -prune \) | sort | sudo xargs rm -r
  when: mattermost_exists.stat.exists

- name: Unpack mattermost archive.
  unarchive:
    src: /tmp/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz
    dest: /opt/
    copy: no
  args:
    creates: /opt/mattermost/bin/platform

- name: Create system group
  group:
    name: "{{ mattermost_system_group }}"
    state: present

- name: Create system user
  user:
    name: "{{ mattermost_system_user }}"
    group: "{{ mattermost_system_group }}"
    system: yes
    state: present
    create_home: no

- name: Apply mattermost config.json template
  template:
    src: mattermost-config.json.j2
    dest: /opt/mattermost/config/config.json
    owner: "{{ mattermost_system_user }}"
    group: "{{ mattermost_system_user }}"
    mode: 0644
  when: not mattermost_exists.stat.exists

- name: Change mattermost directory permissions
  file:
    path: /opt/mattermost
    state: directory
    owner: "{{ mattermost_system_user }}"
    group: "{{ mattermost_system_user }}"
    recurse: yes

- name: Place systemd unit
  template:
    src: "mattermost.service.j2"
    dest: /etc/systemd/system/mattermost.service

- name: Enable systemd service
  systemd:
    name: mattermost
    daemon_reload: yes
    enabled: yes
    state: restarted
