---
- name: Copy nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure nginx default configuration files are deleted
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/nginx/conf.d/default.conf"
    - "/etc/nginx/conf.d/ssl.conf"
    - "/etc/nginx/conf.d/virtual.conf"
    - "/etc/nginx/sites-available"
    - "/etc/nginx/sites-enabled"

- name: Apply nginx config template for selected http type
  template:
    src: "mattermost-nginx-{{ mattermost_http_type }}.conf.j2"
    dest: /etc/nginx/conf.d/mattermost.conf
  notify: restart nginx
